server:
  port: 7000

eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**  