server:
  port: 9001

spring:
  application:
    name: User

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:mysql://localhost:3306/airlift
    username: root
    password: Admin@123